#!/bin/bash

while [[ $# -gt 0 ]]; do
    case $1 in
        -n|--limit)
            ARG_LIMIT="$2"
            shift 2
            ;;
        -p|--present)
            ARG_PRESENT="$2"
            shift 2
            ;;
        -s|--since)
            ARG_SINCE="$2"
            shift 2
            ;;
        -t|--until)
            ARG_UNTIL="$2"
            shift 2
            ;;
        *)
            echo "Invalid argument: $1"
            exit 1
            ;;
    esac
done

if [[ -n $ARG_LIMIT ]]; then
    # -n
    # Tell last how many lines to show.
    LOGINS_LINE_LIMIT="$ARG_LIMIT"
fi

if [[ -n $ARG_PRESENT ]]; then
    # -p
    # Display the users who were present at the specified time.
    # This is like using the options --since and --until together with the same time.
    LOGINS_PRESENT=$(date -d "$ARG_PRESENT" +%s)    
fi

if [[ -n $ARG_SINCE ]]; then
    # -s
    # Display the state of logins since the specified time.
    LOGINS_SINCE=$(date -d "$ARG_SINCE" +%s)
fi

if [[ -n $ARG_UNTIL ]]; then
    # -t
    # Display the state of logins until the specified time.
    LOGINS_UNTIL=$(date -d "$ARG_UNTIL" +%s)
fi

LOG_FILES="/var/log/auth.log*"

zcat -f $LOG_FILES | grep "authentication failure" | grep -v "ftp" | sort -r | while read ISO_DATE MSG; do
	if [[ -n $LOGINS_LINE_LIMIT ]]; then
		if [[ $LOGINS_LINE_LIMIT -gt 0 ]]; then
			LOGINS_LINE_LIMIT=$((LOGINS_LINE_LIMIT - 1))
		else
			break
		fi
	fi

	DATE=$(date -d "$ISO_DATE" "+%a %b %d %H:%M")
	EPOCH_TIME=$(date -d "$ISO_DATE" +%s)

    if [[ -n $LOGINS_PRESENT ]]; then
        if ! [[ $LOGINS_PRESENT -le $EPOCH_TIME && $EPOCH_TIME -le $(( $LOGINS_PRESENT + 60 )) ]]; then
            continue 
        fi
    fi

    if [[ -n $LOGINS_SINCE ]]; then
        if [[ $EPOCH_TIME -lt $LOGINS_SINCE ]]; then 
            break
        fi
    fi

    if [[ -n $LOGINS_UNTIL ]]; then
        if [[ $EPOCH_TIME -gt $LOGINS_UNTIL ]]; then 
            continue  
        fi
    fi

    HOUR=$(echo $DATE | awk '{print $4}')
    USER=$(echo $MSG | awk '{print $NF}' | awk -F'=' '{print $2}')

    echo  $USER  "seat0"  "login screen"  $DATE - $HOUR  "(00:00)"
done 
